/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface LbsContainer {
    }
    interface LbsCustom {
    }
}
declare global {
    interface HTMLLbsContainerElement extends Components.LbsContainer, HTMLStencilElement {
    }
    var HTMLLbsContainerElement: {
        prototype: HTMLLbsContainerElement;
        new (): HTMLLbsContainerElement;
    };
    interface HTMLLbsCustomElement extends Components.LbsCustom, HTMLStencilElement {
    }
    var HTMLLbsCustomElement: {
        prototype: HTMLLbsCustomElement;
        new (): HTMLLbsCustomElement;
    };
    interface HTMLElementTagNameMap {
        "lbs-container": HTMLLbsContainerElement;
        "lbs-custom": HTMLLbsCustomElement;
    }
}
declare namespace LocalJSX {
    interface LbsContainer {
    }
    interface LbsCustom {
    }
    interface IntrinsicElements {
        "lbs-container": LbsContainer;
        "lbs-custom": LbsCustom;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "lbs-container": LocalJSX.LbsContainer & JSXBase.HTMLAttributes<HTMLLbsContainerElement>;
            "lbs-custom": LocalJSX.LbsCustom & JSXBase.HTMLAttributes<HTMLLbsCustomElement>;
        }
    }
}
